[build]
  base = "web"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# (Optional) Single Page App routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
