[build]
base = "web"
command = "npm install && npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
